onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /riscv_pipeline_tb/clk
add wave -noupdate /riscv_pipeline_tb/reset
add wave -noupdate /riscv_pipeline_tb/debug_current_pc_if_stage
add wave -noupdate /riscv_pipeline_tb/debug_instr_id_stage
add wave -noupdate /riscv_pipeline_tb/debug_alu_result_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_zero_flag_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_branch_target_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_jump_target_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_branch_taken_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_alu_control_code_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_alu_src_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_rdata1_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_rdata2_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_imm_ext_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_rd_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_reg_write_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_mem_read_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/debug_mem_write_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/clk
add wave -noupdate /riscv_pipeline_tb/DUT/reset
add wave -noupdate /riscv_pipeline_tb/DUT/debug_current_pc_if_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_instr_id_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_alu_result_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_zero_flag_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_branch_target_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_jump_target_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_branch_taken_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_alu_control_code_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_alu_src_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_rdata1_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_rdata2_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_imm_ext_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_rd_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_reg_write_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_mem_read_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/debug_mem_write_out_ex_stage
add wave -noupdate /riscv_pipeline_tb/DUT/if_instr_to_reg
add wave -noupdate /riscv_pipeline_tb/DUT/if_pc_plus_4_to_reg
add wave -noupdate /riscv_pipeline_tb/DUT/if_current_pc_to_reg
add wave -noupdate /riscv_pipeline_tb/DUT/id_instr_from_reg
add wave -noupdate /riscv_pipeline_tb/DUT/id_pc_plus_4_from_reg
add wave -noupdate /riscv_pipeline_tb/DUT/id_pc_from_reg
add wave -noupdate /riscv_pipeline_tb/DUT/id_rdata1
add wave -noupdate /riscv_pipeline_tb/DUT/id_rdata2
add wave -noupdate -radix decimal /riscv_pipeline_tb/DUT/id_imm_ext
add wave -noupdate -radix decimal /riscv_pipeline_tb/DUT/id_rs1_addr
add wave -noupdate -radix unsigned /riscv_pipeline_tb/DUT/id_rs2_addr
add wave -noupdate /riscv_pipeline_tb/DUT/id_rd_addr
add wave -noupdate /riscv_pipeline_tb/DUT/id_reg_write
add wave -noupdate /riscv_pipeline_tb/DUT/id_mem_read
add wave -noupdate /riscv_pipeline_tb/DUT/id_mem_write
add wave -noupdate /riscv_pipeline_tb/DUT/id_alu_op
add wave -noupdate /riscv_pipeline_tb/DUT/id_alu_src
add wave -noupdate /riscv_pipeline_tb/DUT/id_branch
add wave -noupdate /riscv_pipeline_tb/DUT/id_jump
add wave -noupdate /riscv_pipeline_tb/DUT/id_result_src
add wave -noupdate /riscv_pipeline_tb/DUT/id_funct3
add wave -noupdate /riscv_pipeline_tb/DUT/id_funct7
add wave -noupdate /riscv_pipeline_tb/DUT/id_opcode
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_pc_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_pc_plus_4_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_rdata1_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_rdata2_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_imm_ext_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_rs2_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_rd_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_reg_write_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_mem_read_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_mem_write_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_alu_op_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_alu_src_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_branch_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_jump_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_result_src_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_funct3_out
add wave -noupdate /riscv_pipeline_tb/DUT/id_ex_funct7_out
add wave -noupdate /riscv_pipeline_tb/DUT/alu_operand_b
add wave -noupdate /riscv_pipeline_tb/DUT/alu_control_code
add wave -noupdate /riscv_pipeline_tb/DUT/alu_result
add wave -noupdate /riscv_pipeline_tb/DUT/zero_flag
add wave -noupdate /riscv_pipeline_tb/DUT/less_than_flag
add wave -noupdate /riscv_pipeline_tb/DUT/overflow_flag
add wave -noupdate /riscv_pipeline_tb/DUT/branch_target_ex
add wave -noupdate /riscv_pipeline_tb/DUT/jump_target_ex
add wave -noupdate /riscv_pipeline_tb/DUT/branch_taken_ex
add wave -noupdate /riscv_pipeline_tb/DUT/pc_src_sel_ex
add wave -noupdate /riscv_pipeline_tb/DUT/wb_RegWriteW
add wave -noupdate /riscv_pipeline_tb/DUT/wb_rdW
add wave -noupdate /riscv_pipeline_tb/DUT/wb_resultW
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {28992 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 356
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {375360 ps} {463680 ps}
